### ISSUE TITLE
.initOps should be in onLoad, not onAttach

### ISSUE THREAD

**Issue by hongooi73** [decisionpatterns/operator.tools#1]
I'm trying to use operator.tools (well, really formula.tools, but that loads operator.tools first) in a package. If I import the function I want (`rhs`), I get an error when I call it:

```
Error in .local(x, ...) : ~ does not appear to be an operator.
```

Tracing this back through the code, it looks like the cause is that `formula.tools::rhs` tries to lookup a list of operators that is created by operator.tools. However, the code that creates this list is in `operator.tools:::.initOpts`, which is only called in `operator.tools:::.onAttach`. This means it isn't called when I only _load_ the package, but don't _attach_ it.

Can this startup code be moved into `.onLoad`? Best practice when writing packages is to modify the search path as little as possible, so I'd rather not attach formula.tools and operator.tools if possible.

**Comment by ctbrown** [comment]
I will take a look at it.  It seems possible and a good idea.

C-
